sudo: required

language: cpp

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  - source ci/travis/build-$TRAVIS_OS_NAME.sh

deploy:
  provider: releases
  file: <package-file>
  skip_cleanup: true
  overwrite: true

  api_key:
    secure: <encrypted-github-token>

  on:
    tags: true